### ISSUE TITLE
stripe_event webhook not working

### ISSUE THREAD

**Issue by jespr** [jasoncharnes/pay#24]
I seem to have a problem when trying to hit `/webhooks/stripe`. I get the following:

```
Started POST "/webhooks/stripe" for 127.0.0.1 at 2018-11-23 21:43:19 -0800

ActionController::RoutingError (No route matches [POST] "/webhooks/stripe"):

actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
railties (5.2.1) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

I have tried installing stripe_event directly in my project, without `pay` installed - and that seems to work fine. My app is running on ruby 2.5.3p105 and rails 5.2.1.

The version of pay I'm using is the latest, pointing to github using:
`gem 'pay', github: 'jasoncharnes/pay'`

Any ideas what could be going on? :/

**Comment by excid3** [comment]
You can run `rails routes` and see if the Pay gem's routes show up in there. This is still a work-in-progress gem right now that we've got some kinks to fix (like this).

**Comment by jespr** [comment]
@excid3 I should of course have mentioned that I had done that. It does show up, albeit without the POST in front of it. So I forked the gem to change the routes file to contain the following (added the `:via`:

```
Rails.application.routes.draw do
  mount StripeEvent::Engine, at: '/webhooks/stripe', via: :post
end
```

But still the same problem. I guess I'll hold of with using this gem for a bit :)

**Comment by excid3** [comment]
I figured you might have. I'm going to take a look when I get the chance. It is probably something simple, but I'm not sure what it would be.

**Comment by jespr** [comment]
I might dig a little further as well - no rush :)

**Comment by excid3** [comment]
@jespr would you give `excid3/pay` a try instead? I think I haven't pushed any of my changes up to jason's repo lately and I've been actively working on the fork for a while.

Looks like it's working in my fork:

```bash
           webhooks_stripe POST   /webhooks/stripe(.:format)                                                               stripe_event/webhook#event
```

**Comment by jespr** [comment]
@excid3 sorry for the delay in getting back to you :) That does indeed work! Thank you
