### ISSUE TITLE
NoMethodError: undefined method `credentials' for #<Russ::Application:0x000055bed0ab3c88>

### ISSUE THREAD

**Issue by daniel-0318** [jasoncharnes/pay#80]
Hi there,
I am install pay in my Rails application following the step to use with Devise gem, but when run ``` rails db:migrate```

```
$ rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
NoMethodError: undefined method `credentials' for #<Russ::Application:0x000055bed0ab3c88>
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pay-1.0.0/lib/pay/env.rb:32:in `credentials'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pay-1.0.0/lib/pay/env.rb:17:in `find_value_by_name'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pay-1.0.0/lib/pay/stripe.rb:27:in `private_key'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pay-1.0.0/lib/pay/stripe.rb:14:in `setup'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/pay-1.0.0/lib/pay/engine.rb:33:in `block in <class:Engine>'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:413:in `instance_exec'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:413:in `block in make_lambda'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:197:in `block (2 levels) in halting'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:601:in `block (2 levels) in default_terminator'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:600:in `catch'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:600:in `block in default_terminator'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:198:in `block in halting'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `block in invoke_before'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `each'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:507:in `invoke_before'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:130:in `run_callbacks'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/reloader.rb:87:in `prepare!'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/application/finisher.rb:61:in `block in <module:Finisher>'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `instance_exec'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `run'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/initializable.rb:59:in `block in run_initializers'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `each'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `call'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/initializable.rb:58:in `run_initializers'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/application.rb:353:in `initialize!'
/home/daniel0318/app/russ/config/environment.rb:5:in `<top (required)>'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `block in require'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/application.rb:329:in `require_environment!'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/application.rb:445:in `block in run_tasks_blocks'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:238:in `block in invoke_prerequisites'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `each'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:236:in `invoke_prerequisites'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
/home/daniel0318/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/home/daniel0318/.rbenv/versions/2.5.5/bin/rake:23:in `load'
/home/daniel0318/.rbenv/versions/2.5.5/bin/rake:23:in `<main>'
Tasks: TOP => db:migrate => environment
```

and before when run```  rails pay:install:migrations ```

```
Copied migration 20190724182043_create_subscriptions.pay.rb from pay
Copied migration 20190724182044_add_fields_to_billable.pay.rb from pay
Copied migration 20190724182045_create_charges.pay.rb from pay
```

And the ```/config/environment.rb ``` and on line 5 where the error is:

```
# Load the Rails application.
require_relative 'application'

# Initialize the Rails application.
Rails.application.initialize!
```

In my Gemfile Add:
```
gem 'pay'
gem 'stripe', '< 5.0', '>= 2.8'
gem 'stripe_event', '~> 2.2'
```
Also add ``` include Pay::Billable ``` in my user model and secret stripe_api_key both public and private.

**Comment by daniel-0318** [comment]
Error fixed, when creating a new project changing the rails version 5.1.4 in` gemfile` for `rails 5.2.3` and copy and paste the folder `config` and all files (no folders) in the root to the principal project.
